package com.michaelRunzler.ARK.android.util.DialogFragments;

/**
 * Abstract class for handling user interaction events from dialog fragment subclass implementations.
 */
public abstract class DialogActionEventHandler
{
    /**
     * Indicates what type of user interaction result was generated by said interaction with a dialog
     * element. Descriptions are as follows:
     *
     * POSITIVE: The user selected the button declared as 'Positive' in the dialog box. For Y/N style dialogs, this is the equivalent of the 'Yes' button.
     * NEGATIVE: The user selected the button declared as 'Negative' in the dialog box. For Y/N style dialogs, this is the equivalent of the 'No' button.
     * NEUTRAL: The user selected the button declared as 'Neutral' in the dialog box. This button's implementation is per-dialog.
     * SUBMITTED: The user submitted the dialog's result query. This is usually handled by the POSITIVE type, but in some cases this may need to be separate.
     * CANCELLED: The user cancelled the dialog without submitting a result. This is usually handled by the NEGATIVE type, but in some cases this may need to be separate.
     * CLOSED: The user force-closed the dialog somehow, for example, by using the back button. This should be handled by the android OS in most cases, but it's present if needed.
     */
    public enum ResultID
    {
        POSITIVE, NEGATIVE, NEUTRAL,
        SUBMITTED, CANCELLED, CLOSED
    }

    /**
     * Handles an event from a user interaction with a dialog.
     * @param resultID the ResultID code indicating the type of result the interaction generated
     * @param result one or multiple optional returned objects from the interaction process
     */
    public abstract void handleEvent(ResultID resultID, Object... result);
}
